config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/coming_soon', to: 'pages#coming_soon'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update, :delete] do
    resources :reviews, only: [:index]
    resources :enquiries, only: [:index]
    resources :jobs, only: [:index]
  end
  resources :enquiries, except: [:index, :show]
  resources :reviews, except: [:index, :show]
  resources :jobs, except: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :enquiries
  has_many :contractor_enquiries, foreign_key: :contractor_id, class_name: "Enquiry"
  has_many :contractors, foreign_key: :contractor_id, class_name: "Enquiry"
  has_many :users, foreign_key: :user_id, class_name: "Enquiry"
  has_many :users, through: :contractors
  has_many :contractors, through: :users
  has_many :user_professions
  has_many :professions, through: :user_professions
  has_many :reviews
  has_many :jobs, through: :enquiries
  has_many :contractor_jobs, through: :contractor_enquiries, source: :job
  has_one_attached :image
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :email, presence: true, uniqueness: true
  # validates :phone_number, presence: true
  # validates :location, presence: true
  # validates :contractor_name, presence: true, if: :contractor?

  def contractor?
    contractor
  end

  def add_profession(profession_id)
    UserProfession.create(user: self, profession: Profession.find(profession_id))
    self.contractor = true
  end

  def become_contractor
    self.contractor = true
  end

  def update_professions(array)
    array.each do |element|
      unless element == "" || self.user_professions.find_by_profession_id(Profession.find_by_name(element).id)
        self.add_profession(Profession.find_by_name(element).id)
      end
    end
  end

  def pending_enquiries
    enquiries = self.contractor ? self.contractor_enquiries.where(confirmed: [nil, false]) : self.enquiries.where(confirmed: [nil, false])
    enquiries.where('date >= ?', Date.today).order(:date)

  end

  def pending_jobs
    # jobs = self.contractor ? self.contractor_jobs.where(completed: [nil, false]) : self.jobs.where(completed: [nil, false])
    jobs = self.contractor ? self.contractor_jobs : self.jobs
    jobs.sort_by { |job| job.time}
    jobs.where('time >= ?', Time.now).order(:time)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.joins(:professions).where(professions: { id: params[:profession]})
    @profession = Profession.find(params[:profession])
    @enquiry = Enquiry.new()
  end

  def new
    User.new()
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @user.become_contractor if params[:contractor]
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:profession_ids]
      @user.update_professions(params[:user][:profession_ids])
    end
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:contractor_name, :bio, :logo)
  end
end

app/views/users/_pop_up.html.erb
<div class="pop-up-background">
  <div class="pop-up-content">
    <div class="pop-up-form">
      <%= simple_form_for [ @enquiry ] do |f| %>
      <%= f.input :property_address, label: "Dirección" %>
      <%= f.input :information, label: "Descripción del trabajo" %>
      <%= f.input :date, html5: true %>
      <%= f.input :timeslot, label: "Selecciona su disponibilidad", collection: ['AM', 'PM', 'Todo el día']%>
      <%= f.hidden_field "contractor_id", value: @contractor.id %>
      <%= f.hidden_field "title", value: "#{@profession.name} en #{@enquiry.property_address}" %>
      <%= f.submit "Confirmar" %>
    <% end %>
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.contractor %>
    <%= simple_form_for @user do |f| %>
    <%= f.input :contractor_name %>
    <%= f.input :bio %>
    <%= f.input :logo %>
    <%= f.association :professions, collection: Profession.all_names %>
    <%= f.submit %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="true-cont-all">
  <div class="left-all-prof">
    <div class="headers-contractor">
      <h2>Profesionales Disponibles</h2>
      <p>Podrás comunicarte con estos profesionales, ajustar detalles, o cambiar la tarea despues de confirmar tu reserva.</p>
    </div>
    <% @users.each do |user| %>
      <div class="contractor-card">
        <div class="contractor-card-left">
          <% if current_user.image.attached? && user == current_user %>
            <%= cl_image_tag current_user.image.key, alt: "alttext", class: "avatar_prof" %> <br>
          <% elsif user.image.attached? %>
            <%= cl_image_tag user.image.key, alt: "alttext", class: "avatar_prof" %> <br>
          <% else %>
            <%= image_tag "avatar.png", alt: "alttext", class: "avatar_prof" %> <br>
          <% end %>
          <%= link_to "Perfil completo", user_path(user), class: "perfil-completo-btn" %>
        </div>
        <div class="contractor-card-right">
          <div class="contractor-right-top">
            <div class="contractor-right-text">
              <h3 class="name-contractor"><%= user.contractor_name %></h3>
              <div class="prof-elite">
                <%= image_tag "elite.png", alt: "alttext", class: "elite-icon" %>
                <p class="prof-text">Profesional de Élite</p>
              </div>

              <div class="prof-elite">
                <%= image_tag "star.png", alt: "alttext", class: "star-icon" %>
                <p class="prof-text">100% Reseñas Positivas</p>
              </div>

              <div class="prof-elite">
                <%= image_tag "seguro.png", alt: "alttext", class: "seguro-icon" %>
                <p class="prof-text">100% Seguro</p>
              </div>
            </div>
            <div class="contractor-right-price-confirm">
              <h5 class="contractor-price">20€/hr</h5>
              <%= link_to "Confirmar", new_enquiry_path(contractor_id: user, profession: @profession), class: "confirm-prof-btn", remote: true, method: :get %>
            </div>
          </div>
          <p class="user-bio"><%= user.bio %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="right-all-prof">
    <div class="sort-by-contractor">
      <p class="ordenar-por">ORDENAR POR:</p>
      <%= form_tag users_path, method: :get, class: "form-inline" do %>
        <%= select_tag "sort", options_for_select(%w(Recomendado Disponibles)) %>
      <% end %>
    </div>

    <div class="choose-a-date-time">
      <div class="day-contractor">
        <div class="header-icon-sort">
          <%= image_tag "calendar.png", alt: "alttext", class: "calendar-img" %>
          <h5>Fecha deseada</h5>
        </div>
        <div class="top-two-day">
          <%= link_to "Urgente", "#", class: "sort-btn top-btn-fst" %>
          <%= link_to "Mañana", "#", class: "sort-btn top-btn-snd" %>
        </div>
        <div class="bottom-two-day">
          <%= link_to "Esta semana", "#", class: "sort-btn" %>
          <%= link_to "Escoge fecha", "#", class: "sort-btn escoge-fecha" %>
        </div>
      </div>

      <div class="time-contractor">
        <div class="header-icon-sort">
          <%= image_tag "reloj.png", alt: "alttext", class: "reloj-img" %>
          <h5>Hora deseada</h5>
        </div>
        <div class="cont-times">
          <div class="top-two-time">
            <%= link_to "08:00 - 13:00", "#", class: "sort-btn morning-time" %>
            <%= link_to "14:00 - 21:00", "#", class: "sort-btn" %>
          </div>
          <p class="especifica-una-hora">o especifica una hora</p>
          <div class="bottom-time">
            <%= form_tag users_path, method: :get, class: "form-inline time-form" do %>
              <%= select_tag "sort", options_for_select(%w(09:00 10:00 11:00 12:00 13:00 14:00 15:00 16:00 17:00 18:00 19:00)) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="image-foot foot-col">
    <%= image_tag "logo_white.png", alt: "Fiducia logo blanco", class: "white-logo-foot" %>
  </div>
  <div class="first-foot-col foot-col">
    <h5>TRABAJA CON NOSOTROS</h5>
    <%= link_to "Empleo", "#", class: "foot-link"  %> <br>
    <%= link_to "Establecimientos asociados", "#", class: "foot-link"  %> <br>
    <%= link_to "Repartidores", "#", class: "foot-link"  %> <br>
    <%= link_to "Fiducia Business", "new_user_session_path", class: "foot-link"  %> <br>
  </div>
  <div class="second-foot-col foot-col">
    <h5>AYUDA</h5>
    <%= link_to "Preguntas frecuentes", "#", class: "foot-link" %> <br>
    <%= link_to "Contacto", "#", class: "foot-link" %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.contractor_name %>