config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/coming_soon', to: 'pages#coming_soon'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update, :delete] do
    resources :reviews, only: [:index]
    resources :enquiries, only: [:index]
    resources :jobs, only: [:index]
  end
  resources :enquiries, except: [:index, :show]
  resources :reviews, except: [:index, :show]
  resources :jobs, except: [:index, :show]
end

app/views/shared/_contractor_profile.html.erb
<div class="true-cont-all">


  <div class="container">
  <div class="greeting">
    <h1>Hola <%= @user.first_name.capitalize %>!</h1>
  </div>

    <div class="container-profile">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item nav-label-custom">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#enquiries" role="tab" aria-controls="home" aria-selected="true">Encuestas Pendientes</a>
          </li>
          <li class="nav-item nav-label-custom">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#jobs" role="tab" aria-controls="profile" aria-selected="false">Encuestas Confirmadas</a>
          </li>
        </ul>

        <div class="tab-content" id="myTabContent">
          <div id="enquiries" class="tab-pane fade show active">
            <% @user.pending_enquiries.each do |enquiry| %>
              <div class="contractor-profile-card">
                <div class="hoverable d-flex">
                  <div class="contractor-card-date">
                    <h5><%= enquiry.convert_date %></h5>
                    <p><%= enquiry.timeslot %></p>
                  </div>
                  <div class="contractor-card-job-info">
                    <h6><%= enquiry.title %></h6>
                    <p><%= enquiry.property_address %></p>
                  </div>
                  <div class="contractor-card-user-info">
                    <h6>Para</h6>
                    <p><%= enquiry.user.first_name.capitalize %> <%= enquiry.user.last_name.capitalize %></p>
                  </div>

                </div>
              <div class="contractor-enquiry-card-info hidden">
                <p><%= enquiry.information %></p>
              </div>
                <div class="contractor-enquiry-card-form">
                  <%= simple_form_for @job,
                  wrapper: :inline_form,
                  html: { class: 'form-inline' } do |f| %>
                    <%= f.input :time, collection: enquiry.generate_times %>
                    <%= f.hidden_field "enquiry_id", value: enquiry.id %>
                    <%= f.submit "Book This Job", class: 'btn-book-job' %>
                  <% end %>
                </div>
              </div>

            <% end %>
          </div>
          <div id="jobs" class="tab-pane fade in active">
            <% @user.pending_jobs.each do |job| %>
              <div class="contractor-profile-card">
                <div class="hoverable d-flex">
                  <div class="contractor-card-date">
                    <h5><%= job.display_date %></h5>
                    <p><%= job.display_time %></p>
                  </div>
                  <div class="contractor-card-job-info">
                    <h6><%= job.enquiry.title %></h6>
                    <p><%= job.enquiry.property_address %></p>
                  </div>
                  <div class="contractor-card-user-info">
                    <h6>Para</h6>
                    <p><%= job.enquiry.user.first_name.capitalize %> <%= job.enquiry.user.last_name.capitalize %></p>
                  </div>
                </div>
                <div class="hidden">
                  <%= job.enquiry.information %>
                </div>
                <div class="contractor-enquiry-card-cancel">
                  <% if !job.completed %>
                    <%= link_to "Cancel Job",
                                job_path(job),
                                method: :delete,
                                data: { confirm: "¿Estás seguro?" },
                                class: 'btn-cancel-job' %>
                    <%= link_to "Mark as complete",
                                job_path(job, completed: true),
                                method: :patch,
                                class: 'btn-book-job' %>
                  <% else %>
                    <p>Completado</p>
                  <% end %>
                </div>
            <% end %>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
  <% if user_signed_in? == false %>
    <li class="nav-item" id="urgente">
      <%= link_to "Reparación Urgente", users_path(profession: 3), class: "nav-link" %>
    </li>
    <li class="nav-item" id="incio-mobil">
      <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
    </li>
  <% else %>
    <li class="nav-item dropdown" id="avatar-mobil">
      <% if current_user.image.attached? %>
        <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Conviertete en un trabajador", edit_user_path(current_user, contractor: true), class: "dropdown-item" %>
        <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
        <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mensajes", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.image.attached? %>
            <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Conviertete en un trabajador", edit_user_path(current_user, contractor: true), class: "dropdown-item" %>
            <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
            <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Reparación Urgente", users_path(profession: 3), class: "nav-link trabaja-btn" %>
        </li>
        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user_profile.html.erb
<div class="container">

  <div class="greeting">
    <h1>Hola <%= @user.first_name.capitalize %>!</h1>

  </div>

  <div class="container-profile">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item nav-label-custom">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#enquiries" role="tab" aria-controls="home" aria-selected="true">Encuestas Pendientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#jobs" role="tab" aria-controls="profile" aria-selected="false">Encuestas Confirmadas</a>
        </li>
      </ul>

      <div class="tab-content" id="myTabContent">
        <div id="enquiries" class="tab-pane fade show active">
          <% @user.pending_enquiries.each do |enquiry| %>
            <div class="contractor-profile-card">
              <div class="contractor-card-date">
                <h5><%= enquiry.convert_date %></h5>
                <p><%= enquiry.timeslot %></p>
              </div>
              <div class="contractor-card-job-info">
                <h6><%= enquiry.title %></h6>
                <p><%= enquiry.property_address %></p>
              </div>
              <div class="contractor-card-user-info">
                <h6>Para</h6>
                <p><%= enquiry.user.first_name.capitalize %> <%= enquiry.user.last_name.capitalize %></p>
              </div>
              <div class="contractor-enquiry-card-form">
                <p>Esperando respuesta</p>
              </div>
            </div>
          <% end %>
        </div>

        <div id="jobs" class="tab-pane fade in active">
          <% @user.pending_jobs.each do |job| %>
            <div class="contractor-profile-card">
              <div class="contractor-card-date">
                <h5><%= job.display_date %></h5>
                <p><%= job.display_time %></p>
              </div>
              <div class="contractor-card-job-info">
                <h6><%= job.enquiry.title %></h6>
                <p><%= job.enquiry.property_address %></p>
              </div>
              <div class="contractor-card-user-info">
                <h6>Con</h6>
                <p><%= job.enquiry.contractor.contractor_name %></p>
              </div>
              <div class="contractor-enquiry-card-cancel">
                <% if job.completed %>
                  <p>Completado</p>
                <% else %>
                  <p>Por completar</p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>