config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/coming_soon', to: 'pages#coming_soon'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update, :delete] do
    resources :reviews, only: [:index]
    resources :enquiries, only: [:index]
    resources :jobs, only: [:index]
  end
  resources :enquiries, except: [:index, :show]
  resources :reviews, except: [:index, :show]
  resources :jobs, except: [:index, :show]
end

app/views/pages/coming_soon.html.erb
<div class="box-for-all">
<div class="container-coming-soon">
  <%= image_tag "under_construction.png", alt: "renovaciones, proximamente", class: "under-construction" %>
</div>
  <h5 class="bajo-construccion">Esta página está bajo construcción</h5>
  <p class="proximamente">Proximamente podrás realizar tu renovación con Fixenova.</p>
</div>

app/views/pages/home.html.erb
<div class="top-box">
  <div class="topsec">
    <div class="top-text">
      <h2 class="frase-pegadiza">Reformas y reparaciones, al alcance de tus dedos.</h2>
      <p class="descripcion-landing">No te molestes, recibe ayuda de miles de profesionales de confianza para cualquier reparación, reforma o limpieza de tu hogar.</p>
    </div>
    <div class="landing-top-images">
      <%= image_tag "shape_landing.png", alt: "imagen decorativa", class: "landing-square" %>
      <%= image_tag "regandoo.png", alt: "señor regando", class: "regando-pic" %>
    </div>

  </div>
  <%= form_tag root_path, method: :get, class: "search-bar" do %>
    <%= text_field_tag :query,
        params[:query],
        id: "home-search-field",
        class: "form-control searches",
        placeholder: "Busca tu reparación"
      %>
  <% end %>
  <%= link_to "¡Empieza tu renovacion!", coming_soon_path, class: "coming-soon" %>
</div>

<div class="cont1">
  <h2 class= "frase-pegadiza" id="dispon">Reparaciones disponibles a tu alrededor</h2>
  <div class="cont">
    <div class="row">
      <% @professions.each do |profession| %>
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 mb-4">
          <div class="card">
            <% if profession.name == "Albañilería" %>
              <%= image_tag "Albanileria.jpg", alt: "alttext" %>
            <% else %>
              <%= image_tag "#{profession.name}.jpg", alt: "alttext" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= profession.name %></h5>
              <%= link_to "Precio desde #{profession.cost.to_i} €", users_path(profession: profession), class: "btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="join-us-box">
  <h2 class="frase-pegadiza" id="unete">¡Únete a Fixenova!</h2>
  <div class="join-cards">
    <div class="join-card" id="top-join-card">
      <div class="top-part-join-card">
        <%= image_tag "empieza.png", alt: "empieza", class: "join-card-image" %>
      </div>
      <div class="join-card-bottom">
        <h4 class="join-heading">Profesionales</h4>
        <h5>Las horas que tu quieras</h5>
        <p>Impulsa tu negocio colaborando con nosotros y benefíciate de nuestras herramientas, nuestra tecnología y nuestra base de clientes para tener la ciudad entera a tus pies.</p>
      </div>
      <%= link_to "Trabaja con nosotros", new_user_registration_path, class: "join-btn" %>
    </div>

    <%= image_tag "landingline.png", alt: "alttext", class: "landingline" %>

    <div class="join-card">
      <%= image_tag "profesional.png", alt: "alttext", class: "join-card-image" %>
      <div class="join-card-bottom">
        <h4 class="join-heading">Empieza Proyectos</h4>
        <h5>Contrata profesionales</h5>
        <p>Mejora tu hogar a un coste minimo y escoge el profesional que más le guste. Con Fixenova tienes más visibilidad de tus costes y tus pagos estan 100% asegurados.</p>
      </div>
      <%= link_to "¡Registrate ya!", new_user_registration_path, class: "join-btn2" %>
    </div>
  </div>
</div>

<div class="box-financing">
  <h2 id="unete">¿Buscas Financiamiento?</h2>
  <div class="banner-financiamiento">
    <%= image_tag "financing.png", alt: "Financiamiento Para Remodelar su Casa", class: "image-fianacing" %>
    <p>Fixenova te da la oportunidad de solicitar financiamiento para cubrir los gastos de sus proyectos en su hogar.</p>
    <%= link_to "Solicitar Financiamiento" , coming_soon_path %>
  </div>
</div>


<div class="footer">
  <div class="image-foot foot-col">
    <%= image_tag "logo_white.png", alt: "Fiducia logo blanco", class: "white-logo-foot" %>
  </div>
  <div class="first-foot-col foot-col">
    <h5>TRABAJA CON NOSOTROS</h5>
    <%= link_to "Empleo", "#", class: "foot-link"  %> <br>
    <%= link_to "Establecimientos asociados", "#", class: "foot-link"  %> <br>
    <%= link_to "Repartidores", "#", class: "foot-link"  %> <br>
    <%= link_to "Fixenova Business", new_user_registration_path, class: "foot-link"  %> <br>
  </div>
  <div class="second-foot-col foot-col">
    <h5>AYUDA</h5>
    <%= link_to "Preguntas frecuentes", "#", class: "foot-link" %> <br>
    <%= link_to "Contacto", "#", class: "foot-link" %>
  </div>
</div>

app/views/pages/profile.html.erb
<% if !@user.contractor %>
  <%= render "shared/user_profile" %>
<% else %>
  <%= render "shared/contractor_profile" %>
<% end %>